services:
  app:
    build: .
    container_name: dependability-app
    ports:
      - '3000:3000'
      - '3005:3005'
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASS: rootpassword
      SEND_EMAILS: 'false'
      DB_NAME: dependability_tracker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: [
        'sh',
        '-c',
        'npm run seed && npm run seed-callouts-365 && npm run sendInvite "test@test.com" && npm run start'
        # 'npm run dev'
      ]
  db:
    image: mariadb:11
    container_name: dependability-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: dependability_tracker
      MARIADB_USER: app_user
      MARIADB_PASSWORD: rootpassword
      MARIADB_ROOT_PASSWORD: thisisasecretpassword

    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h localhost -u$DB_USER -p$DB_PASS|| exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data:
