import type {Metadata} from 'next';
import {Html, Head, Main, NextScript} from 'next/document';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function Document() {
  return (
    <Html lang="en" className="bg-slate-950 text-gray-300">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
