import './globals.css';
import Image from 'next/image';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const styles = {
  body: ' bg-slate-950 text-gray-200 flex min-h-screen flex-col items-center justify-start p-5',
  logo: 'w-[450px] h-auto',
  imgWidth: 450,
  imgHeight: 200
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + styles.body}>
        <Image
          id="logo"
          alt="SEA-TAC"
          className={styles.logo}
          width={styles.imgWidth}
          height={styles.imgHeight}
          src="/assets/images/seatac-dark.png"
        />
        {children}
      </body>
    </html>
  );
}
